### ISSUE TITLE
Error with CommandPanels plugin

### ISSUE THREAD

**Issue by CrazyCloudCraft** [TonimatasMCDEV/PerWorldPlugins#1]
Hi, if i use your Plugin together with CommandPanel some things didn't work  
1. the /cpc - command to close a panel
2. the placeholders like msg= console= etc. 

More info here:
https://github.com/rockyhawk64/CommandPanels/issues/222

**Comment by TonimatasMCDEV** [comment]
**Test this version:**
[PerWorldPlugins-1.0.1.4.zip](https://github.com/TonimatasMCDEV/PerWorldPlugins/files/9255224/PerWorldPlugins-1.0.1.4.zip)

**Comment by TonimatasMCDEV** [comment]
> Hi, if i use your Plugin together with CommandPanel some things didn't work
> 
> 1. the /cpc - command to close a panel
> 2. the placeholders like msg= console= etc.
> 
> More info here: [rockyhawk64/CommandPanels#222](https://github.com/rockyhawk64/CommandPanels/issues/222)
Test this version:
[PerWorldPlugins-1.0.1.4.zip](https://github.com/TonimatasMCDEV/PerWorldPlugins/files/9256808/PerWorldPlugins-1.0.1.4.zip)

**Comment by TonimatasMCDEV** [comment]
> Hi, if i use your Plugin together with CommandPanel some things didn't work
> 
> 1. the /cpc - command to close a panel
> 2. the placeholders like msg= console= etc.
> 
> More info here: [rockyhawk64/CommandPanels#222](https://github.com/rockyhawk64/CommandPanels/issues/222)

Hello?

**Comment by CrazyCloudCraft** [comment]
I will test it...
